$color = rgba(18, 18, 18, 1)
$inner_color = rgba(18, 18, 18, 0.66)
$outer_color = rgba(215, 135, 255, 1)
$font_color = rgba(218, 218, 218, 1)
$placeholder_color = rgba(218, 218, 218, 0.7)
$check_color = rgba(95, 215, 215, 1)
