background            #121212
foreground            #dadada

# black
color0  #121212
color8  #6c6c6c

# red
color1  #ff5f87
color9  #ff5f87

# green
color2  #5fd75f
color10 #5fd75f

# yellow
color3  #ffd700
color11 #ffd700

# blue
color4  #5fafd7
color12 #5fafd7

# magenta
color5  #d787ff
color13 #d787ff

#cyan
color6  #5fd7d7
color14 #5fd7d7

#white
color7  #dadada
color15 #eeeeee


